TEST

diff --git a/helm-charts/falcon-sensor/templates/tests/test-sidecar-sensor-running.yaml b/helm-charts/falcon-sensor/templates/tests/test-sidecar-sensor-running.yaml
--- a/helm-charts/falcon-sensor/templates/tests/test-sidecar-sensor-running.yaml
+++ b/helm-charts/falcon-sensor/templates/tests/test-sidecar-sensor-running.yaml
@@ -38,11 +38,14 @@ spec:
 
             echo "Waiting 15 seconds to allow pod time to initialize before running test"
             sleep 15
-            kubectl get pods -n busybox
-            kubectl get events -n busybox
-            kubectl describe pods -n busybox
-            kubectl get pods -n busybox --field-selector=status.phase!=Running -o jsonpath="{.items[*].spec.containers[*].name}" 
-
+            KUBECMD2=$(kubectl get pods -n busybox --field-selector=status.phase!=Running -o jsonpath="{.items[*].spec.containers[*].name}"
+            if ! echo "${KUBECMD2}" | grep -q "crowdstrike-falcon-container"; then
+                echo "[\033[0;31mFAIL\033[0m]: crowdstrike-falcon-container sidecar container is NOT injected"
+                echo "${KUBECMD2}"
+                exit 1
+            else
+                echo "[\033[0;32mOK\033[0m]: crowdstrike-falcon-container sidecar container is injected"
+            fi
             exit 0
         fi
       securityContext:
